import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Layout } from '../components/Layout'
import { ModeSwitcher } from '../components/ModeSwitcher'

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Blandins Pomodoro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ModeSwitcher/>
  </Layout>
  )
}

export default Home
